# Generated by Django 5.1.4 on 2025-01-07 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_groups_customuser_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(
                default="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nu merge :/"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
