# Generated by Django 5.1.4 on 2025-01-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_post_content_post_date_post_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="description",
        ),
    ]
